# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
envlist = lint, static, unit

[vars]
src_path = {toxinidir}/src
tst_path = {toxinidir}/tests
all_path = {[vars]src_path} {[vars]tst_path}
uv_flags = --frozen --isolated --extra=dev

[testenv]
allowlist_externals = uv
basepython = python3
setenv =
  PYTHONPATH = {toxinidir}:{toxinidir}/lib:{[vars]src_path}
  PY_COLORS=1

[testenv:lock]
commands = uv lock --upgrade --no-cache

[testenv:fmt]
commands = uv run {[vars]uv_flags} ruff check --fix-only {[vars]all_path}

[testenv:lint]
commands = uv run {[vars]uv_flags} ruff check {[vars]all_path}

[testenv:static]
skip_install = True
commands = uv run {[vars]uv_flags} pyright {[vars]src_path}

[testenv:unit]
commands =
  uv run {[vars]uv_flags} coverage run --source={[vars]src_path} -m pytest {[vars]tst_path}/unit {posargs}
  uv run {[vars]uv_flags} coverage report
