[tox]
no_package = True
skip_missing_interpreters = True
env_list = fmt, lint, static, unit

[vars]
src_path = {toxinidir}/src/
tst_path = {toxinidir}/tests/
all_path = {[vars]src_path} {[vars]tst_path}
uv_flags = --frozen --isolated

[testenv]
allowlist_externals =
    uv
basepython = python3
setenv =
    PYTHONPATH = {toxinidir}/src
    PY_COLORS = 1
passenv =
    PYTHONPATH

[testenv:fmt]
description = Run code formatting
commands =
    uv run {[vars]uv_flags} --with ruff ruff format {[vars]all_path}
    uv run {[vars]uv_flags} --with ruff ruff check --fix {[vars]all_path}

[testenv:lint]
description = Run linting checks
commands =
    uv run {[vars]uv_flags} --with ruff ruff format --check {[vars]all_path}
    uv run {[vars]uv_flags} --with ruff ruff check {[vars]all_path}

[testenv:static]
description = Run static type checking
commands =
    uv run {[vars]uv_flags} --with pyright pyright {[vars]src_path}
[testenv:unit]
description = Run unit tests
commands =
    uv run {[vars]uv_flags} --with pytest --with pytest-cov pytest {[vars]tst_path}/unit/ {posargs} -v --tb=short --cov=canonical_service_mesh --cov-report=term-missing --cov-fail-under=85
