name: Quality Gates

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      charm:
        type: string
        description: Charm to run quality gates for (directory name under charms/)
  # Run the quality checks periodically
  # FIXME: adjust the frequency as needed once we have actual gates in place
  # schedule:
  #   - cron: "0 0 * * Tue"


jobs:
  quality-gates:
    name: Run quality gates
    uses: canonical/observability/.github/workflows/charm-quality-gates.yaml@v2
    with:
      charm-path: charms/${{ github.event.inputs.charm }}
    secrets: inherit
