name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**
    paths:
      # If you update these paths, also update the filters in the 'changes' job below
      - charms/istio-k8s/**
      - charms/istio-beacon-k8s/**
      - charms/istio-ingress-k8s/**

jobs:
  changes:
    name: Detect changed charms
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      charms: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            charms/istio-k8s:
              - charms/istio-k8s/**
            charms/istio-beacon-k8s:
              - charms/istio-beacon-k8s/**
            charms/istio-ingress-k8s:
              - charms/istio-ingress-k8s/**

  pull-request:
    name: PR (${{ matrix.charm-path }})
    needs: changes
    if: ${{ needs.changes.outputs.charms != '[]' }}
    strategy:
      matrix:
        charm-path: ${{ fromJSON(needs.changes.outputs.charms) }}
      fail-fast: false
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v2
    with:
      charm-path: ${{ matrix.charm-path }}
    secrets: inherit
