name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  discover-charms:
    name: Discover charms
    runs-on: ubuntu-latest
    outputs:
      charms: ${{ steps.discover.outputs.charms }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: charms
          sparse-checkout-cone-mode: true
      - id: discover
        run: echo "charms=$(ls -d1 charms/* | jq -Rsc 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  update-lib:
    name: Check libraries (${{ matrix.charm-path }})
    needs: discover-charms
    strategy:
      matrix:
        charm-path: ${{ fromJSON(needs.discover-charms.outputs.charms) }}
      fail-fast: false
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v2
    with:
      charm-path: ${{ matrix.charm-path }}
    secrets: inherit

