name: Release Charm to Edge and Publish Libraries

on:
  workflow_dispatch:
    inputs:
      charm:
        type: choice
        description: Which charm to release
        options:
          - all
          - istio-beacon-k8s
          - istio-ingress-k8s
          - istio-k8s
  push:
    branches:
      - main
      - 'track/**'
    paths:
      - 'charms/**'

jobs:
  set-charms:
    name: Set charm matrix
    runs-on: ubuntu-latest
    outputs:
      charms: ${{ steps.set-charms.outputs.charms }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: charms
          sparse-checkout-cone-mode: true
      - name: Set charms matrix
        id: set-charms
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.charm }}" != "all" ]]; then
            echo 'charms=[{"charm-path": "charms/${{ inputs.charm }}", "charm-name": "${{ inputs.charm }}"}]' >> "$GITHUB_OUTPUT"
          else
            echo "charms=$(ls -d1 charms/* | jq -Rsc '[split("\n")[:-1][] | {("charm-path"): ., ("charm-name"): ltrimstr("charms/")}]')" >> "$GITHUB_OUTPUT"
          fi

  release:
    name: Release (${{ matrix.charm-path }})
    needs: set-charms
    strategy:
      matrix:
        include: ${{ fromJSON(needs.set-charms.outputs.charms) }}
      fail-fast: false
    permissions:
      actions: read
      security-events: write
      contents: write
    uses: canonical/observability/.github/workflows/charm-release.yaml@metallb-fix
    secrets: inherit
    with:
      charm-path: ${{ matrix.charm-path }}
      git-tag-prefix: ${{ matrix.charm-name }}
      default-track: dev
      provider: microk8s
