set allow-duplicate-recipes
set allow-duplicate-variables
import? 'rocks.just'

# Upstream project repository, used by 'update', 'add-version' and 'govulncheck'.
source_repo := 'kiali/kiali'

[private]
@default:
  just --list
  echo ""
  echo "For help with a specific recipe, run: just --usage <recipe>"
